GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email":"user@email.com",
  "password": "123456"
}

###
GET http://localhost:3000/users/06d1513b-0c5a-4582-b647-f3611dd160fb

###
GET http://localhost:3000/users/email/user@email.com
###
PUT http://localhost:3000/users/06d1513b-0c5a-4582-b647-f3611dd160fb
Content-Type: application/json

{
  "email":"user@email.com",
  "password": "123456"
}
###
DELETE http://localhost:3000/users/06d1513b-0c5a-4582-b647-f3611dd160fb