GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email":"user@email.com",
  "password": "123456"
}

###
GET http://localhost:3000/users/50c7a240-e3b1-4839-98fa-ff85b6fe02ae

###
GET http://localhost:3000/users/email/user@.com